#!/bin/bash

if [ ! -d "/data/dalmatinerfe" ]; then
    mkdir -p /data/dalmatinerfe
fi

if [ ! -d "/data/dalmatinerfe/log" ]; then
    mkdir -p /data/dalmatinerfe/log
fi

# Sort out file permissions
if [[ $(id dalmatinerfe 2>/dev/null) ]] ;then
    chown -R dalmatinerfe:dalmatinerfe /data/dalmatinerfe
fi

CONFFILE=/data/dalmatinerfe/etc/dfe.conf

if [ ! -f "${CONFFILE}" ]
then
    echo "Creating new configuration from example file."
    cp ${CONFFILE}.example ${CONFFILE}
else
    echo "Please update your configuration according to the update manual!"
fi

OT=/data/dalmatinerfe/etc/rules.ot
if [ ! -f "${OT}" ]
then
    echo "none() -> drop." > ${OT}
fi
